/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Coordinador;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author keilor
 */
public class VentanaRegistro extends javax.swing.JFrame {

    private Coordinador miCoordinador;

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crearPerfil_btn = new javax.swing.JButton();
        registrar_btn = new javax.swing.JButton();
        cancelar_btn = new javax.swing.JButton();
        limpiar_btn = new javax.swing.JButton();
        nombre_txt = new javax.swing.JTextField();
        username_txt = new javax.swing.JTextField();
        contrasena_txt = new javax.swing.JPasswordField();
        confirmarContrasena_txt = new javax.swing.JPasswordField();
        validar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        genero_cbx = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Username:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("Confirmar:");

        crearPerfil_btn.setText("Crear Perfil");
        crearPerfil_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPerfil_btnActionPerformed(evt);
            }
        });

        registrar_btn.setText("Registrar");

        cancelar_btn.setText("Cancelar");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });

        limpiar_btn.setText("Limpiar");

        contrasena_txt.setToolTipText("Contraseña");
        contrasena_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasena_txtActionPerformed(evt);
            }
        });

        confirmarContrasena_txt.setToolTipText("ConfirmarContraseña");

        validar_btn.setText("Validar");

        jLabel1.setText("Genero:");

        genero_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(genero_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(validar_btn))
                                .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confirmarContrasena_txt)
                                .addComponent(contrasena_txt))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crearPerfil_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiar_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(genero_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validar_btn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contrasena_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(confirmarContrasena_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearPerfil_btn)
                    .addComponent(registrar_btn)
                    .addComponent(cancelar_btn)
                    .addComponent(limpiar_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPerfil_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPerfil_btnActionPerformed
        String nom = nombre_txt.getText();
        String gen = String.valueOf(genero_cbx.getSelectedItem());
        char g = gen.charAt(0);
        String user = username_txt.getText();
        char confPass[] = confirmarContrasena_txt.getPassword();
        char pass[] = contrasena_txt.getPassword();
        char mant = 'N'; // Por defecto no se mantine la sesion de un usuario recien creado, se puede cambiar al iniciar sesion.
        String contra = miCoordinador.cifrarPass(pass); // Envio char[] y recibo String
        if (contra == "ERROR de Cifrado") {
            JOptionPane.showMessageDialog(this,"\nNo se permite el character [ . ]");
        }
        else if((miCoordinador.verificarPass(confPass,pass)==false))
            JOptionPane.showMessageDialog(this,"\nContraseñas no coinciden");
        
        else if((nom.equals("")) | (gen.equals("")) | (user.equals(""))| (contra.equals("")))
                JOptionPane.showMessageDialog(this,"\nNo se permiten campos vacios");
        else {
            String resultado = miCoordinador.crearUsuario(nom, g, user, contra, mant);
            JOptionPane.showMessageDialog(this, resultado);
        }

    }//GEN-LAST:event_crearPerfil_btnActionPerformed

    private void contrasena_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasena_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasena_txtActionPerformed

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
        VentanaInicio inicio = new VentanaInicio();
        inicio.setVisible(true);
        inicio.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_cancelar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JPasswordField confirmarContrasena_txt;
    private javax.swing.JPasswordField contrasena_txt;
    private javax.swing.JButton crearPerfil_btn;
    private javax.swing.JComboBox<String> genero_cbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton limpiar_btn;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JButton registrar_btn;
    private javax.swing.JTextField username_txt;
    private javax.swing.JButton validar_btn;
    // End of variables declaration//GEN-END:variables
/*
    @Override
    public void actionPerformed(ActionEvent ae) {
        
        if (ae.getSource() == crearPerfil_btn) {
            String cod = codigo_txt.getText();
            String nom = nombre_txt.getText();
            String user = username_txt.getText();
            char contra[] = contrasena_txt.getPassword();
            String resultado = miCoordinador.crearUsuario(cod, nom, user, contra);
            JOptionPane.showMessageDialog(this, "hola");

        }
    }
     */
    public void setCoordinador(Coordinador miCoordinador) {
        this.miCoordinador = miCoordinador;
    }
}
